//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrickCheckerSolutions.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SystemMessages
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
